version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  ngslims-net:

services:
  ngslims-DB:
    container_name: ngslims-DB
    image: mysql:8
    command:
      mysqld
        --explicit_defaults_for_timestamp=1
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --skip-character-set-client-handshake
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./schemas:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: ngslims
      MYSQL_ROOT_PASSWORD: ngsLIMS_123
      MYSQL_USER: ngslims
      MYSQL_PASSWORD: ngslims123
      TZ: "Asia/Tokyo"
    restart: always
    networks:
      - ngslims-net

  ngslims:
    container_name: ngslims
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: ngslims
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "8080:80"
    depends_on:
      - "ngslims-DB"
    restart: always
    networks:
      - ngslims-net
